### ISSUE TITLE
devextreme-angular

### ISSUE THREAD

**Issue by mgechev** [angular/ngcc-validation#115] opened 2019-08-03 01:49 UTC
```
ERROR in ./node_modules/jszip/lib/readable-stream-browser.js
Module not found: Error: Can't resolve 'stream' in '/Users/mgechev/Projects/ngcc-validation/devextreme-angular-ngcc/node_modules/jszip/lib'
```

**Comment by petebacondarwin** [comment] 2019-08-12 15:09
I think this would be fixed by ignoring the `node.js` built-ins perhaps?

**Comment by JoostK** [comment] 2019-08-12 15:24
@petebacondarwin We should already be doing that since https://github.com/angular/angular/pull/31872. The problem is that renovate has been choking on this repo since it was switched to locked Angular builds, so we haven't incorporated Angular updates for 10 days. With #153 merged we should hopefully be back on track.

**Closed** 2019-10-11 23:22 UTC
